services:
  - type: web
    name: pricy-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
